(part "LMQ66420MC5RXBRQ1"
    (packageRef "LMQ66430R5RXBR")
    (interface
        (port "1" (symbPinId 1) (portName "EN_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NC_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VIN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "PGND") (portType INOUT))
        (port "7" (symbPinId 7) (portName "SW") (portType INOUT))
        (port "8" (symbPinId 8) (portName "BOOT_1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "NC_4") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VCC") (portType INOUT))
        (port "11" (symbPinId 11) (portName "VOUT/FB") (portType INOUT))
        (port "12" (symbPinId 12) (portName "NC_5") (portType INOUT))
        (port "13" (symbPinId 13) (portName "MODE/SYNC") (portType INOUT))
        (port "14" (symbPinId 14) (portName "PG") (portType INOUT))
        (port "15" (symbPinId 15) (portName "GND/DAP") (portType INOUT))
        (port "16" (symbPinId 16) (portName "NC_6") (portType INOUT))
        (port "17" (symbPinId 17) (portName "BOOT_2") (portType INOUT))
        (port "18" (symbPinId 18) (portName "NC_7") (portType INOUT))
        (port "19" (symbPinId 19) (portName "EN_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "LMQ66420MC5RXBRQ1")
    (property "Mouser_Part_Number" "595-MQ66420MC5RXBRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LMQ66420MC5RXBRQ1?qs=1Kr7Jg1SGW%2FJb4To9Gytbg%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Switching Voltage Regulators Automotive, 36-V, 2-A low-EMI synchronous step-down converter with 1.5-uA IQ 14-VQFN-FCRLF -40 to 150")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/lmq66420-q1?HQS=ti-null-null-sf-df-pf-sep-wwe&DCM=yes?hkey=EF798316E3902B6ED9A73243A3159BB0")
    (property "symbolName1" "LMQ66420MC5RXBRQ1")
)
